### PR TITLE
Correct scopes for comments

### PR DESCRIPTION
**Pull request by mrmlnc**
Hello, @davidrios,

I think we must understand that a comment is a comment, and not a string. Just buffered and unbuffered comments. For example, JavaScript when block and single-line comments have one scope.

``` json
"comment-block": {
    "name": "comment.block.js"
},
"comment-block-doc": {
    "name": "comment.block.documentation.js"
},
"comment-line": {
    "name": "comment.line.js"
}
```

Also `invalid.illegal.comment.comment.block.jade` have double `comment` in scope name.

**Before fix (Sublime Text 3 with you package):**

image

**After fix (Sublime Text 3 with you package):**

image

### CODE REVIEW

**Comment by davidrios** [comment]
This is intentional, so you can have a visual indication of what will be a part of the final rendered HTML. Do you have another comment scope that will accomplish that on most color themes?

**Comment by mrmlnc** [comment]
@davidrios, I think we shouldn't talk here about highlighting, because it's a base scope. For example, buffered and unbuffered comments in Less ([LESS.tmLanguage#L145-L178](https://github.com/danro/LESS-sublime/blob/master/LESS.tmLanguage#L145-L178)) or Sass ([SASS.tmLanguage#L73-L88](https://github.com/n00ge/sublime-text-haml-sass/blob/master/SASS/Syntaxes/SASS.tmLanguage#L73-L88)).

**Comment by davidrios** [comment]
So, what are the dire consequences of having an incorrectly named scope?

**Comment by mrmlnc** [comment]
@davidrios, formally - no consequences. In practice, people expect to see color of the comment.

In any case, I just suggested the changes. You can reject it 🐼

**Comment by mrmlnc** [comment]
Closed as outdated.

**Pull request closed without merging**
